### ISSUE TITLE
Extension seems to not work anymore 

### ISSUE THREAD

**Issue by dc4665** [duffey/spicetify-furigana-lyrics#1]
Extension is not working anymore and does not display the furigana. 

Below is the information about my Spotify and Spicetify : 
Spotify for Windows (64 bit)
1.2.36.959.g04bf500c
Spicetify v2.36.10
Theme: marketplace
Extensions: spicetify-furigana-lyrics.js
Custom apps: marketplace

**Comment by marcelstacha** [comment]
have you had any luck or is there nothing we can do ?

**Comment by dc4665** [comment]
> have you had any luck or is there nothing we can do ?

Do you have the same issue ? Just want to make sure that it is not only my installation or whatsoever.

**Comment by marcelstacha** [comment]
yes after checking the marketplace i found that furigana addon which seemed perfect, but it seems to do absolutely nothing.
i have not used it in the past. 2 weeks ago yours stopped working ? i only can think of downgrading but i dont know if this would bring new issues + you cant disable spotify updates, right ?

**Comment by dc4665** [comment]
> yes after checking the marketplace i found that furigana addon which seemed perfect, but it seems to do absolutely nothing. i have not used it in the past. 2 weeks ago yours stopped working ? i only can think of downgrading but i dont know if this would bring new issues + you cant disable spotify updates, right ?

Yeah basically it was working for a time, but just stopped to work maybe 3 weeks or a month ago. To be honest I didn't try to downgrade, as it is just an hassle with Spotify automatic upgrade + spicetify which decides sometimes to not run. Well at least thanks for confirming that it does not work as well for you.

I just hope that @duffey  will decide to look at it one day, or that a new plugin doing the same thing will appear.

**Comment by duffey** [comment]
Hey, Spotify updated their CSS which broke the extension. The CSS class for lyrics is now some random string, so it seems like it will break again if I don't do something more complicated, but I went ahead and applied a simple fix for now. Sorry it took so long. I haven't been listening to music lately.
