### ISSUE TITLE
Last spotify update breaking the extension

### ISSUE THREAD

**Issue by dc4665** [duffey/spicetify-furigana-lyrics#2]
Hi again, really sorry to bother you again, but it seems that the last Spotify update broke your extension again. The furigana are not displayed. Will appreciate if you find the time to fix it, really like your extension ! 

This is my specs : 
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
Spicetify v2.36.13

**Comment by itswilliboy** [comment]
Probably the same issue as #1.
